#!/usr/bin/env python
import sys, os, time
import tweepy
keys = dict(
consumer_key='9hFwwiXoRVTARgoCCMuQic5YK',
consumer_secret='KEpid8RyUS3Bn0s3YxwQ9uXdDTrUlKoxi9I3Czf8z6KT8mZ2Ri',
access_token='4251589695-r5tfHdWGyUfsjGoMyyFQsxhRfaGku3JSUUE43Jc ', 
access_token_secret='5AcCRULOLgw1rYBXALK6uepsqexOXmjil4Vj3JZronHs3'
)

user = "Zibaswr"

auth = tweepy.OAuthHandler(keys['consumer_key'], keys['consumer_secret'])
auth.set_access_token(keys['access_token'], keys['access_token_secret'])
api = tweepy.API(auth)

def tweet():
	message=input("tweet: ")
	api.update_status(message)
	time.sleep(1000)
if __name__ == "__main__":
	while 1:
		tweet()
